import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import HeaderWrapper from "./_components/HeaderWrapper";
import SidebarWrapper from "./_components/SideBarWrapper";
import { AuthProvider } from "./_components/context/AuthContext";
import { CookiesProvider } from "next-client-cookies";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Buy Me a Coffee",
  description: "Generated by Team Pentacode",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.variable}>
        <HeaderWrapper />
        <SidebarWrapper />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
